### ISSUE TITLE
Cannot upload files through Metalnx when using irods_rule_engine_plugin_logical_quotas

### ISSUE THREAD

**Issue by darthtux** [irods-contrib/metalnx-web#180] opened 2020-12-04 17:02 UTC
All uploads through Metalnx fail when the iRODS logical quota plugin is configured in the server_config.json file.  The error received is `Upload failed. Resource(s) might be full.`

Relevant logs from the Metalnx Docker container:
```
2020-12-04 16:46:27 ERROR UploadServiceImpl:142 - Upload stream failed from Metalnx to the data grid. io exception copying buffers
2020-12-04 16:46:27 ERROR UploadController:133 - DataGridException uploading file
2020-12-04 16:46:27 WARN  UploadController:134 - DataGridException uplaoding file, will pass back as warning
com.emc.metalnx.core.domain.exceptions.DataGridException: Upload failed. Resource(s) might be full.
```

This is produced in rodsLog:
```
Dec  4 10:46:27 pid:50076 remote addresses: 10.31.4.83, 172.17.0.3 ERROR: unordered_map::at: key not found
Dec  4 10:46:27 pid:50076 remote addresses: 10.31.4.83, 172.17.0.3 ERROR: unordered_map::at: key not found.
```

Using iput to the same directory completes as expected.  

The only way I have found to get around the issue is to remove the iRODS logical quota plugin configuration from the server_config.json file.  

Using
Metalnx 2.2.0
iRODS server 4.2.8-1
irods-rule-engine-plugin-logical-quotas 4.2.8.0-1

**Comment by trel** [comment] 2020-12-04 17:59
Definitely first we've heard of this.   Will work to reproduce.

**Comment by michael-conway** [comment] 2020-12-04 18:13
I'd immediately look to differences between streaming and direct io there
may be a difference between these server codepaths for this policy?

**Comment by korydraughn** [comment] 2020-12-14 21:40
I have verified that this error is produced when attempting to upload via metalnx.

`iput` and `istream` work as expected and do not produce any error messages.

@michael-conway What API is metalnx invoking to upload a file?

**Comment by michael-conway** [comment] 2020-12-14 21:46
It's DataObjInp open/write/close. We can do some testing against your
server we were using last week?

**Comment by korydraughn** [comment] 2020-12-14 21:52
Sure, but that server is running tip of 4-2-stable. I'll need to roll that instance back to 4.2.8.

**Comment by michael-conway** [comment] 2020-12-14 22:02
no don't do that maybe we can test on the docker framework? What I was
getting at was the ability to see the logs etc on the iRODS side if I run
some tests, or we can lay out how to test this, in terms of an assertion
we'd want to make, how to set up the sequence of events and replicate this
on the level of the Jargon streaming I/O code, because that's where the
issue would occur.

**Comment by korydraughn** [comment] 2020-12-14 22:09
Dang, I rolled the container back to 4.2.8, but I'll restore it to tip of 4-2-stable for Jargon testing.

We're supposed to be getting on a call some time this week, so lets discuss the details then. Sound good?

**Comment by trel** [comment] 2021-03-06 03:06
related to https://github.com/irods/irods_rule_engine_plugin_logical_quotas/issues/30 - perhaps fixed in https://github.com/irods/irods_rule_engine_plugin_logical_quotas/commit/38da2a27cf09ac08384e8c4fa95771e6aea4ba23 ?

will need to try metalnx against 4-2-stable to confirm/deny.

**Comment by korydraughn** [comment] 2022-09-03 17:23
I've verified that Metalnx is able to upload files against Logical Quotas v4.2.9.0.

This issue can be closed.

**Closed** 2022-09-03 17:33 UTC
Labels: bug
