### ISSUE TITLE
docker image not working?

### ISSUE THREAD

**Issue by dimitargnikolov** [irods-contrib/metalnx-web#23] opened 2017-09-07 17:38 UTC
I set up the Docker image according to the instructions in the wiki and I am able to run the container from DockerHub.

```
ubuntu@irods-host:~$ sudo docker container ls
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                    NAMES
a3825561769c        metalnx/metalnx-web:1.1.0-latest   "/bin/bash /start_..."   47 seconds ago      Up 46 seconds       0.0.0.0:8080->8080/tcp   lucid_meitner
```
```
ubuntu@irods-host:~$ sudo docker logs -f a3825561769c
Creating user "metalnx"...

PostgreSQL stand-alone backend 9.2.15
backend> backend> Creating database "metalnx"...

PostgreSQL stand-alone backend 9.2.15
backend> backend> Granting access to database "metalnx" for user "metalnx"...

PostgreSQL stand-alone backend 9.2.15
/usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
backend> backend> 2017-09-07 17:21:11,579 CRIT Supervisor running as root (no user in config file)
2017-09-07 17:21:11,598 INFO RPC interface 'supervisor' initialized
2017-09-07 17:21:11,598 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-09-07 17:21:11,598 INFO supervisord started with pid 24
2017-09-07 17:21:12,600 INFO spawned: 'postgresql' with pid 27
2017-09-07 17:21:12,601 INFO spawned: 'tomcat' with pid 28
2017-09-07 17:21:14,557 INFO success: postgresql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-07 17:21:14,557 INFO success: tomcat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

It seems like everything is working but if I go to http://localhost:8080/emc-metalnx-web I get a 403 Access Denied error.

I have an irods instance for testing running on localhost. I ran the docker with:

```
docker run -d \
-p 8080:8080 \
-e IRODS_HOST="172.17.0.1" \
-e IRODS_PORT=1247 \
-e IRODS_ZONE="tempZone" \
-e IRODS_USER="rods" \
-e IRODS_PASS="rods" \
metalnx/metalnx-web:1.1.0-latest
```
172.17.0.1 is the IP of the docker0 interface on my machine. 

I can run iCommands on the host machine with the above parameters, but it seems like metalnx can't reach the irods instance from the container. 

Is there a different host I should be using in the docker command above?

**Comment by baoboa** [comment] 2017-10-19 20:59
usually  172.17.0.1  is the ip adresse of the gateway , if the irods provider is a container XXXXXX

use "sudo docker inspect XXXXXX | grep IPAddress"

i did use this container (provider) 

 mjstealey/docker-irods-icommands

with success

**Comment by sgworth** [comment] 2017-10-24 13:35
It has been a while since I have used the docker image.  If my memory
serves you need to connect directly to the metalnx application from
your web browser (after the docker image is running) with the command:

http://<hostname>:8080/emc-metalnx-web/login/

where hostname is the FQN hostname or the IP address of the Docker
image.  This is covered in the Setup section of the Wiki.

**Comment by baoboa** [comment] 2017-10-24 17:32
the problem is when we log in we got that it's impossible to contact the irod server  

we got a message "iRODS not responding" in the login windows

and we got redirected to http://<hostname>:8080/emc-metalnx-web/login/serverNotResponding/

at the same time the container docker.io/metalnx/metalnx-web:1.0-latest is working perfectly

with the same args

 "Env": [
                "IRODS_HOST=172.17.0.3",
                "IRODS_PORT=1247",
                "IRODS_ZONE=tempZone",
                "IRODS_USER=XXXX",
                "IRODS_PASS=XXXX",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

**Comment by michael-conway** [comment] 2017-10-24 18:48
this may be dumb but did you try going to  http://localhost:8080/emc-metalnx-web/login

This may be a bug I was going to look at.

Also, be sure to look in the logs, did you get some other iRODS error?

**Comment by baoboa** [comment] 2017-10-24 21:13
thanks for your reply

i redirect to 8086 , and i got the same thing with http://localhost:8086/emc-metalnx-web/login/
```
docker logs Containerid 
```
didn't show much, where should i look to track a connection problem ?

metalnx:1.0

```log
2017-10-24 17:11:04,838 INFO RPC interface 'supervisor' initialized
2017-10-24 17:11:04,838 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-10-24 17:11:04,839 INFO supervisord started with pid 24
2017-10-24 17:11:05,841 INFO spawned: 'postgresql' with pid 27
2017-10-24 17:11:05,843 INFO spawned: 'tomcat' with pid 28
2017-10-24 17:11:06,845 INFO success: postgresql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-10-24 17:11:06,845 INFO success: tomcat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

metalnx:1.4

```log
2017-10-24 20:52:24,157 INFO RPC interface 'supervisor' initialized
2017-10-24 20:52:24,157 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-10-24 20:52:24,157 INFO supervisord started with pid 26
2017-10-24 20:52:25,160 INFO spawned: 'postgresql' with pid 29
2017-10-24 20:52:25,162 INFO spawned: 'tomcat' with pid 30
2017-10-24 20:52:26,164 INFO success: postgresql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-10-24 20:52:26,164 INFO success: tomcat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

PS: to build the docker file i did this

```docker
#ADD ./emc-metalnx-web.war /usr/share/tomcat/webapps/emc-metalnx-web/emc-metalnx-web.war
RUN yum -y install https://bintray.com/metalnx/rpm/download_file?file_path=emc-metalnx-webapp-1.4.0-9.noarch.rpm
RUN cp /tmp/emc-tmp/emc-metalnx-web.war /usr/share/tomcat/webapps/emc-metalnx-web/emc-metalnx-web.war
```

**Comment by sgworth** [comment] 2017-10-24 21:17
The Tomcat log usually has the most useful information for this purpose.  It should be available via the journalctl command.  I cannot remember without trying if you need to be admin or not.

**Comment by baoboa** [comment] 2017-10-24 21:31
i am not sure 
```
journalctl -M bea3fd2dfc6dab5546562f76f85da850 
No journal files were found.
-- No entries --
```

and in the mount point associated with the container there is no ```/var/log/journal``` but a ```/var/log/supervisord``` which is empty

**Comment by baoboa** [comment] 2017-10-24 21:33
the only other log i find are in ```/var/log/tomcat``` but they didn't show any error

**Comment by michael-conway** [comment] 2017-10-25 18:10
easiest thing to do is to launch it interactively with docker run -i instead of -d and all the logs I think will be right there...it saves a lot of searching.

**Comment by rdwrt** [comment] 2018-08-14 08:29
I have the same issue: 1.0 works fine, 1.1.0 doesn't seem to connect

**Comment by baoboa** [comment] 2018-08-14 09:05
the image is too old now, you can try to rebuild it from the dockerfile

**Comment by rdwrt** [comment] 2018-08-14 15:15
Ok I will. Is it an idea to create automated builds for metalnx, to make it easier to use up-to-date builds?

**Comment by michael-conway** [comment] 2018-08-14 15:25
Yes, that's part of what moving it to the consortium is for...right now I'm
building it internally for NIEHS since we have our own image. building
should be pretty straight-forward though. if you do a mvn package
-Dmaven.test.skip=true it puts everyhting in ../packaging/docker

Then you just say

docker build -t yourrepo/yourimage:yourtag .


Then you can run or push it where you need to go

MC

**Comment by rdwrt** [comment] 2018-08-14 15:55
I built the war, and then the docker container from this repo but when starting the service it misses files in /etc/irods-ext/ and fails

If I check a different repo ( https://github.com/MaastrichtUniversity/metalnx-web/tree/rit-metalnx-web/packaging/docker ) there is a folder irods-ext.

Maybe some recent changes in the master? Is there a recent github tag/branch I can build from?

**Comment by rdwrt** [comment] 2018-08-14 15:59
docker logs metalnx: 

2018-08-14 15:46:59 ERROR ContextLoader:351 - Context initialization failed
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [file:/etc/irods-ext/metalnxConfig.xml]
Offending resource: ServletContext resource [/WEB-INF/applicationContext.xml]; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from URL [file:/etc/irods-ext/metalnxConfig.xml]; nested exception is java.io.FileNotFoundException: /etc/irods-ext/metalnxConfig.xml (No such file or directory)
...

**Comment by michael-conway** [comment] 2018-08-14 16:01
The irods-ext needs to be flown in via a docker mount...check

https://github.com/irods-contrib/metalnx-web/blob/master/CONFIGURATION.md


You can PM me if you need some help standing it up

**Comment by rdwrt** [comment] 2018-08-14 16:03
Ok, the issue then was that I was following the (I guess older) instructions in the wiki. 

https://github.com/Metalnx/metalnx-web/wiki/Docker 

maybe link from there to the new instructions?

**Comment by rdwrt** [comment] 2018-08-14 16:04
specifically: https://github.com/irods-contrib/metalnx-web/wiki/Docker#building-and-running-the-container-locally

**Comment by rdwrt** [comment] 2018-08-14 16:26
Almost there. The old docker had a postgres setup built-in. In the newest dockerfile I need to set this separately? Unclear from https://github.com/irods-contrib/metalnx-web/blob/master/CONFIGURATION.md

**Comment by michael-conway** [comment] 2018-08-14 16:29
Yes, the docker image relies on an external postgres server for production
level deployments.

Just set up a db, then look at metalnx-tools it will do a migration and set
up the tables for you and you're good to go...

See
https://github.com/irods-contrib/metalnx-web/blob/master/src/metalnx-tools/README.md

We've been standing this up along with the ICAT.

**Comment by rdwrt** [comment] 2018-08-14 21:40
got the metalnx container up and running  thanks to the information in this thread, thank you!

**Comment by trel** [comment] 2019-03-03 23:27
resolving this for now - the README.md will cover basic standup.

**Closed by trel** 2019-03-03 23:27 UTC

**Comment by baoboa** [comment] 2019-04-08 06:55
thanks
