### ISSUE TITLE
Redo collection browser

### ISSUE THREAD

**Issue by michael-conway** [irods-contrib/metalnx-web#188] opened 2021-02-12 18:24 UTC
Remove existing collection browse view and replace with Vue.js as in thumbnail viewer.

**Comment by michael-conway** [comment] 2021-02-26 23:53
This is the place to get rid of most of the rest of the Metalnx database and performance can really be improved. I am super keen to take the insights we got from cloud browser and be able to save searches, including from indexing, as collections here. We have use cases.

**Comment by trel** [comment] 2024-12-05 17:04
duplicate of #63

**Closed** 2024-12-05 17:04 UTC
Labels: refactor
