### ISSUE TITLE
Export CSV from Metadata search omits the first row

### ISSUE THREAD

**Issue by hanytran** [irods-contrib/metalnx-web#319] opened 2022-09-01 11:19 UTC
Hi,
I'm not sure if this issue has been reported somewhere else.
The csv file doesn't have the first row of the search result in metadata search.
My solution was changing 1 to 0 in line 227 of file MetadataController.java. It seems this makes exporting start from 1 instead of 0. Please let me know if that's a good fix.

https://github.com/irods-contrib/metalnx-web/blob/main/src/metalnx-web/src/main/java/com/emc/metalnx/controller/MetadataController.java

**Comment by trel** [comment] 2022-09-01 13:18
Appears to have last been touched in https://github.com/irods-contrib/metalnx-web/commit/9478a6696fd5d54905150d4b5f014590fd574a3a as part of related/similar fix/discussion of https://github.com/irods-contrib/metalnx-web/issues/195

But we didn't touch the 1.

**Comment by trel** [comment] 2022-09-01 13:22
Can you share an example search result set, both the metalnx view and the associated csv download?

**Comment by hanytran** [comment] 2022-09-01 13:38
Here you are.

![Screenshot from 2022-09-01 15-36-40](https://user-images.githubusercontent.com/36070041/187927864-1837dd35-c0b3-45bc-9980-2c49b07107d0.png)

![Screenshot from 2022-09-01 15-37-15](https://user-images.githubusercontent.com/36070041/187927958-9579cef6-1550-42da-8c40-87dd6bfb3760.png)

**Comment by trel** [comment] 2022-09-01 13:41
Very good - thanks.

**Comment by korydraughn** [comment] 2022-09-03 15:46
Based on the images, it looks like you're running an old version of Metalnx.

I could not reproduce this issue in Metalnx v2.5.0 or v2.6.0. Please try upgrading to one of those versions and let us know how it goes.

**Comment by hanytran** [comment] 2022-09-03 17:33
Hi, are you using iRODS 4.3? Because I could not find the docker image for 4.3, I'm using iRODS 4.2.5 and this version doesn't work with Metalnx 2.5 or 2.6 in metadata search function (I didn't debug yet), so I downgraded to 2.4 and it works. Besides, I installed the Python Rule Engine to automatically extract metadata from uploaded files.
I will check it again when I'm back to work and let you know.

BTW do we already have a Dockerfile for iRODS 4.3?

**Comment by korydraughn** [comment] 2022-09-03 17:47
If you want to run iRODS 4.3.0 for experimental purposes, you can do that through the testing environment here:
- https://github.com/irods/irods_testing_environment

That repository is what we use to quickly stand up various versions of iRODS in various ways. It contains several docker files and docker compose projects. Below is the link to the projects directory where the docker files are stored:
- https://github.com/irods/irods_testing_environment/tree/main/projects

I'd recommend using the python scripts as documented on the README to experiment with iRODS 4.3.0 first. Once you've done that, you can take what you've learned and apply it to a production deployment.

@alanking gave a talk about the development environment and testing environment at this year's UGM. You can watch the video here:
- https://youtu.be/tm6DY83KWW0

**Comment by korydraughn** [comment] 2022-09-03 17:54
There's also the development environment. That repo contains docker files for compiling and running iRODS too. However, the focus of that repo is for development and so it is not as easy/automated as the testing environment. See the README for more details.
- https://github.com/irods/irods_development_environment

Again, the YouTube video I mentioned in the previous comment covers both repos.

**Comment by hanytran** [comment] 2022-09-03 18:00
Thanks for the hints, I will check them all.

**Comment by hanytran** [comment] 2022-09-06 08:25
@korydraughn, in metadata search, have you ever met the error when there are files having common attributes and owned by 2 different users. Once one of them tries to search, no results return because it failed at getting permission in MetadataService of metalnx. 
Error message: "Could not get permissions for current user: unable to find file under path"
iCommand in docker container is working just fine.
![Screenshot from 2022-09-06 10-22-35](https://user-images.githubusercontent.com/36070041/188585199-8b5379f6-995e-4416-8951-d1a10be1b1a7.png)

**Comment by hanytran** [comment] 2022-09-06 11:48
Could you reproduce that error or just because of my setup?

**Comment by korydraughn** [comment] 2022-09-06 12:22
Without looking into things further, my guess is you don't have permission to read the parent collection of the data object.

Given that I've verified that later versions of Metalnx correctly export the search results and downgrading works for you, I'm going to close this issue.

**Closed** 2022-09-07 20:22 UTC
